modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/Cheos137/ArmorpointsPlusplus/issues/new/choose"

[[mods]]
    modId="armorpointspp"
    version="${version}"
    displayName="ArmorPoints++"
    updateJSONURL="https://api.modrinth.com/updates/xvAim1vw/forge_updates.json"
    displayURL="https://modrinth.com/mod/armorpoints"
    logoFile="icon.png"
    credits="Code: Cheos, Additional Textures: Sopsy_Hallow"
    authors="Cheos"
    displayTest="IGNORE_ALL_VERSION"
    description='''
    A light-weight mod overhauling vanilla ui components
    '''

[[dependencies.armorpointspp]]
    modId="neoforge"
    mandatory=true
    versionRange="[20.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.armorpointspp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.2,1.21)"
    ordering="NONE"
    side="BOTH"
